# Generated by Django 2.2.4 on 2021-02-01 17:02

from django.db import migrations


def define_new_buildings(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    year_new_building = 2015
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= year_new_building
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(define_new_buildings),
    ]
